"use client";

import { ProfileDetails, Onboarding } from "@/components/onboarding";
import { workspaceSchema, liveCouncilSchema, profileSchema, type Profile } from "@/lib/workspace";
import { useEffect, useRef, useState, type ReactNode } from "react";
import { Menu, Sun, Check, ChevronRight, Coffee, Compass, Heart, Leaf, Plus, ShieldCheck, Sparkles, Users, X, BriefcaseBusiness, Fingerprint, CalendarDays, LockKeyhole, SlidersHorizontal, ArrowUp, BookOpen } from "lucide-react";
import { Sheet, SheetContent, SheetTitle, SheetDescription } from "@/components/ui/sheet";

type Kind = "balance" | "opportunity" | "social" | "reflection";
type Opinion = { title: string; opinion: string; stance: string };
type Decision = { id: string; question: string; kind: Kind; saved: boolean; opinions?: Opinion[]; recommendation?: string; critique?: string; mode?: "live" | "preview"; profileSnapshot?: Profile };
const initial: Profile = { name: "", about: "", social: { linkedin: "", instagram: "", website: "" }, priority: "", values: [], weekend: true };
const teams = [
  { name: "Wellbeing", icon: Leaf, color: "green", people: ["EL", "JA", "RO"], specialty: "Energy · habits · balance", insight: "Rest belongs in the plan, too.", members: ["Ellis · Everyday habits", "Jamie · Movement & recovery", "Robin · Mindful perspective"] },
  { name: "Work & ambition", icon: BriefcaseBusiness, color: "sand", people: ["NO", "LI", "AM"], specialty: "Business · career · direction", insight: "Choose the work that moves you forward.", members: ["Noah · Business & strategy", "Liv · Career & growth", "Amir · Practical tradeoffs"] },
  { name: "Relationships", icon: Heart, color: "rose", people: ["MA", "SA", "EV"], specialty: "Friends · family · connection", insight: "Small moments make strong connections.", members: ["Mara · Connection & care", "Sage · Communication", "Evan · Shared experiences"] },
];
const examples = ["Should I work this Saturday or go hiking with Maya?", "Should I take a new startup opportunity?", "Help me plan a weekend with my friends."];
const classify = (q: string): Kind => /offer|startup|career|opportunity|job/i.test(q) ? "opportunity" : /trip|plan|friends|weekend with/i.test(q) ? "social" : /work|saturday|hiking|rest|burnout|proposal/i.test(q) ? "balance" : "reflection";
function perspectives(kind: Kind, profile: Profile) {
  if (kind === "balance") return [
    { title: "Protect your energy", opinion: "Another working weekend takes away your recovery time. A walk and a real break deserve a place in your schedule.", stance: "Supports a break" },
    { title: "Don’t leave a loose end", opinion: "The proposal still matters. A focused review before the weekend could reduce the pressure without taking over Saturday.", stance: "Offers a counterpoint" },
    { title: "Keep the promise to Maya", opinion: "You value time with your people. Keep the walk, and check what timing works for Maya before making a plan.", stance: "Protects connection" },
  ];
  if (kind === "opportunity") return [
    { title: "Ask about everyday life", opinion: "Find out what a normal week looks like. Consider the time it leaves for sleep, movement, and recovery.", stance: "Questions the tradeoff" },
    { title: "Investigate the upside", opinion: "Look for a clear role, strong collaborators, and a skill you want to develop. Compare those with your current path.", stance: "Sees an opportunity" },
    { title: "Consider who shares the change", opinion: "Talk with the people affected by a new schedule or location. Their needs belong in the decision.", stance: "Widens the perspective" },
  ];
  if (kind === "social") return [
    { title: "Leave room to breathe", opinion: "One outdoor activity is enough. An unhurried day can be more restorative than a packed itinerary.", stance: "Prefers simplicity" },
    { title: "Close the week first", opinion: "Write down Monday’s first task before signing off. Leave unfinished work somewhere other than your head.", stance: "Adds a small step" },
    { title: "Find a shared starting point", opinion: "Start with availability and one activity preference. A walk and lunch is a useful proposal, subject to everyone’s review.", stance: "Builds common ground" },
  ];
  return [
    { title: "What will this ask of you?", opinion: "Consider the time and energy each option needs. What could you try without overcommitting?", stance: "Checks capacity" },
    { title: "What outcome matters most?", opinion: `Your current priority is “${profile.priority}” What specific result would move that forward?`, stance: "Challenges the objective" },
    { title: "Who else is affected?", opinion: "Name the people affected by the decision. What should you discuss with them before choosing?", stance: "Includes your people" },
  ];
}
function synthesis(kind: Kind, p: Profile) {
  return kind === "balance" ? (p.weekend ? "Protect your Saturday. Give the proposal one focused hour on Friday, then make room for the hike." : "Set aside 90 focused minutes on Saturday morning, then close the laptop and join Maya at 11.") : kind === "opportunity" ? "Explore before committing. Clarify the role, your financial runway, and the time it leaves for the life you want." : kind === "social" ? "Keep it simple: a late-morning coastal walk, followed by lunch. Review everyone’s availability before agreeing." : `Start with your priority: “${p.priority}” Compare one realistic option with staying as you are. Choose a small, reversible next step.`;
}
function Brand({ small = false }: { small?: boolean }) { return <span className={`brand ${small ? "small" : ""}`}><span className="brand-mark"><i /><i /><i /><i /></span><span>nook<span className="brand-period">.</span></span></span>; }
function Avatar({ text, color = "" }: { text: string; color?: string }) { return <span className={`avatar ${color}`} aria-hidden="true">{text}</span>; }
function Modal({ title, children, onClose, wide }: { title: string; children: ReactNode; onClose: () => void; wide?: boolean }) {
  const opener = useRef<HTMLElement | null>(typeof document !== "undefined" && document.activeElement instanceof HTMLElement ? document.activeElement : null);
  return <Sheet open onOpenChange={open => { if (!open) onClose(); }}><SheetContent className={`modal nook-sheet ${wide ? "wide" : ""}`} showCloseButton={false} aria-describedby={undefined} onCloseAutoFocus={event => {
    event.preventDefault();
    requestAnimationFrame(() => {
      // A replacement sheet owns focus when switching between utility views.
      if (document.querySelector('[data-slot="sheet-content"][data-state="open"]')) return;
      const target = opener.current?.isConnected ? opener.current : document.querySelector<HTMLElement>(".nook-composer textarea:not(:disabled), .nook-utilities button");
      target?.focus();
    });
  }}><div className="modal-heading"><span className="eyebrow">YOUR PERSONAL SPACE</span><button className="icon-button" aria-label="Close sheet" onClick={onClose}><X size={21} /></button></div><SheetTitle asChild><h2>{title}</h2></SheetTitle><SheetDescription className="sr-only">Your Nook preferences and saved information.</SheetDescription>{children}</SheetContent></Sheet>;
}
export default function Home() {
  const [profile, setProfile] = useState(initial);
  const [draft, setDraft] = useState(initial);
  const [decisions, setDecisions] = useState<Decision[]>([]);
  const [plans, setPlans] = useState<Record<string, string>>({});
  const [friends, setFriends] = useState<string[]>([]);
  const [onboardingCompleted, setOnboardingCompleted] = useState(false);
  const [ready, setReady] = useState(false);
  const [storageError, setStorageError] = useState<"unavailable" | "corrupt" | null>(null);
  const [canPersist, setCanPersist] = useState(false);
  const [dialog, setDialog] = useState<"saved" | "you" | "council" | "circle" | "profile" | "plan" | "privacy" | "invite" | null>(null);
  const [question, setQuestion] = useState("");
  const [conversation, setConversation] = useState(false);
  const [mobileMenu, setMobileMenu] = useState(false);
  const menuButton = useRef<HTMLButtonElement>(null);
  const [thread, setThread] = useState<Decision[]>([]);
  const [pendingQuestion, setPendingQuestion] = useState("");
  const composer = useRef<HTMLTextAreaElement>(null);
  const threadEnd = useRef<HTMLDivElement>(null);
  const [busy, setBusy] = useState(false);
  const [aiAvailable, setAiAvailable] = useState(false);
  const [needsSignIn, setNeedsSignIn] = useState(false);
  const [liveEnabled, setLiveEnabled] = useState(false);
  const [councilError, setCouncilError] = useState("");
  const requestController = useRef<AbortController | null>(null);
  const [team, setTeam] = useState<number | null>(null);
  const [message, setMessage] = useState("");
  const [reply, setReply] = useState("");
  const [friend, setFriend] = useState("Maya");
  const friendPlanStatus = plans[friend] || "pending";
  const [shared, setShared] = useState({ availability: true, preference: true });
  const [toast, setToast] = useState("");
  const timer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const toastTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  useEffect(() => {
    try {
      const raw = localStorage.getItem("nook.v1");
      if (raw) {
        const parsed = JSON.parse(raw);
        if (parsed && !parsed.plans && ["pending", "saved", "declined"].includes(parsed.planStatus)) parsed.plans = { Maya: parsed.planStatus };
        const result = workspaceSchema.safeParse(parsed);
        if (result.success) { setProfile(result.data.profile); setOnboardingCompleted(result.data.onboardingCompleted); setDecisions(result.data.decisions); setPlans(result.data.plans); setFriends(result.data.friends); setCanPersist(true); }
        else setStorageError("corrupt");
      } else setCanPersist(true);
    } catch { setStorageError("corrupt"); }
    setReady(true);
    return () => { if (timer.current) clearTimeout(timer.current); if (toastTimer.current) clearTimeout(toastTimer.current); requestController.current?.abort(); };
  }, []);
  useEffect(() => { if (ready && canPersist && onboardingCompleted) try { localStorage.setItem("nook.v1", JSON.stringify({ profile, onboardingCompleted, decisions, plans, friends })); } catch { setStorageError("unavailable"); setCanPersist(false); } }, [ready, canPersist, profile, onboardingCompleted, decisions, plans, friends]);
  const notify = (text: string) => { setToast(text); if (toastTimer.current) clearTimeout(toastTimer.current); toastTimer.current = setTimeout(() => setToast(""), 4000); };
  const close = () => { setDialog(null); setTeam(null); };
  useEffect(() => { if (!mobileMenu) return; const listener = (e: KeyboardEvent) => { if (e.key === "Escape") { setMobileMenu(false); menuButton.current?.focus(); } }; document.addEventListener("keydown", listener); return () => document.removeEventListener("keydown", listener); }, [mobileMenu]);
  useEffect(() => { if (!busy && conversation && !dialog && team === null) composer.current?.focus(); }, [busy, conversation, dialog, team]);
  const edit = () => { setDraft({ ...profile, values: [...profile.values] }); setDialog("profile"); };
  const activate = () => { setConversation(true); };
  useEffect(() => { if (conversation) composer.current?.focus(); }, [conversation]);
  const wasBusy = useRef(false);
  useEffect(() => {
    if (wasBusy.current && !busy && !dialog && team === null) composer.current?.focus();
    wasBusy.current = busy;
  }, [busy, dialog, team]);
  useEffect(() => { threadEnd.current?.scrollIntoView({ behavior: window.matchMedia("(prefers-reduced-motion: reduce)").matches ? "auto" : "smooth", block: "end" }); }, [thread, busy, councilError]);
  useEffect(() => { const controller = new AbortController(); fetch("/api/council", { signal: controller.signal }).then(r => r.ok ? r.json() as Promise<{ available: boolean; requiresSignIn?: boolean }> : null).then(s => { setAiAvailable(Boolean(s?.available)); setNeedsSignIn(Boolean(s?.requiresSignIn)); }).catch(() => {}); return () => controller.abort(); }, []);
  const consult = async (q: string) => {
    if (!q.trim() || busy) return;
    setCouncilError(""); close(); setConversation(true); setQuestion(""); setPendingQuestion(q.trim()); setBusy(true);
    const snapshot = { ...profile, values: [...profile.values] };
    const complete = (result?: { opinions: Opinion[]; recommendation: string; critique: string }) => {
      const d: Decision = { id: crypto.randomUUID(), question: q.trim(), kind: result ? classify(q) : examples.includes(q.trim()) ? classify(q) : "reflection", saved: false, profileSnapshot: snapshot, recommendation: result?.recommendation || synthesis(examples.includes(q.trim()) ? classify(q) : "reflection", snapshot), opinions: result?.opinions || perspectives(examples.includes(q.trim()) ? classify(q) : "reflection", snapshot), critique: result?.critique, mode: result ? "live" : "preview" };
      setThread(old => [...old, d]); setDecisions(old => [d, ...old].slice(0, 30)); setPendingQuestion(""); setBusy(false);
    };
    if (!liveEnabled) { timer.current = setTimeout(() => complete(), 600); return; }
    const controller = new AbortController(); requestController.current = controller;
    try {
      const response = await fetch("/api/council", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ question: q.trim(), profile: { name: snapshot.name, priority: snapshot.priority, values: snapshot.values, weekend: snapshot.weekend, about: snapshot.about }, history: thread.slice(-3).flatMap(d => [{ role: "user", content: d.question.slice(0, 2000) }, { role: "assistant", content: (d.recommendation || synthesis(d.kind, d.profileSnapshot || profile)).slice(0, 2000) }]) }), signal: controller.signal });
      const result = await response.json() as { error?: string; opinions: Opinion[]; recommendation: string; critique: string };
      if (!response.ok) throw new Error(result.error || "The council could not complete this reflection.");
      const parsed = liveCouncilSchema.safeParse(result);
      if (!parsed.success) throw new Error("The council returned an incomplete reflection.");
      complete(parsed.data);
    } catch (error) { if (controller.signal.aborted) return; setQuestion(q.trim()); setBusy(false); setCouncilError(error instanceof Error ? error.message : "Could not reach your council. Please try again."); }
  };
  const showPlan = (name = "Maya") => { setFriend(name); setShared({ availability: true, preference: true }); setDialog("plan"); };
  const saveDecision = (decision: Decision) => {
    setDecisions(old => [{ ...decision, saved: true }, ...old.filter(d => d.id !== decision.id)].slice(0, 30));
    setThread(old => old.map(d => d.id === decision.id ? { ...d, saved: true } : d));
    notify("Your next step is saved.");
  };
  const revisit = (decision: Decision) => { close(); setConversation(true); setThread(old => old.some(d => d.id === decision.id) ? old : [...old, decision]); setQuestion(""); };
  const newConversation = () => { if (busy) return; setThread([]); setQuestion(""); setCouncilError(""); setPendingQuestion(""); setConversation(false); };
  const agentWorkspace = useRef({ onboarded: onboardingCompleted, busy, liveEnabled, savedCount: decisions.filter(d => d.saved).length, connectionCount: friends.length + 2 });
  agentWorkspace.current = { onboarded: onboardingCompleted, busy, liveEnabled, savedCount: decisions.filter(d => d.saved).length, connectionCount: friends.length + 2 };
  useEffect(() => {
    type BrowserTool = { name: string; description: string; inputSchema: object; annotations: { readOnlyHint: boolean; untrustedContentHint: boolean }; execute: (input: unknown) => unknown };
    const context = (document as Document & { modelContext?: { registerTool: (tool: BrowserTool, options: { signal: AbortSignal }) => void | Promise<void> } }).modelContext;
    if (!context?.registerTool) return;
    const lifecycle = new AbortController();
    const register = (tool: BrowserTool) => { try { void Promise.resolve(context.registerTool(tool, { signal: lifecycle.signal })).catch(() => {}); } catch { /* Browser tools are optional; the UI remains usable. */ } };
    register({ name: "read_nook_workspace_status", description: "Read local workspace counts and council mode without exposing private profile content or saved questions.", inputSchema: { type: "object", properties: {}, additionalProperties: false }, annotations: { readOnlyHint: true, untrustedContentHint: false }, execute(input) { if (!input || typeof input !== "object" || Array.isArray(input) || Object.keys(input).length) throw new Error("Expected an empty object."); return { savedReflections: agentWorkspace.current.savedCount, connectionCount: agentWorkspace.current.connectionCount, councilMode: agentWorkspace.current.liveEnabled ? "live" : "preview", friendAgents: "sample" }; } });
    register({ name: "prepare_nook_question", description: "Prepare a question in the visible composer for human review. Does not submit it, invoke AI, or contact anyone.", inputSchema: { type: "object", properties: { question: { type: "string", minLength: 1, maxLength: 1000 } }, required: ["question"], additionalProperties: false }, annotations: { readOnlyHint: false, untrustedContentHint: false }, async execute(input) { if (!input || typeof input !== "object" || Array.isArray(input) || Object.keys(input).length !== 1) throw new Error("Expected only a question."); const question = (input as { question?: unknown }).question; if (typeof question !== "string" || !question.trim() || question.length > 1000) throw new Error("Provide a question under 1,000 characters."); if (!agentWorkspace.current.onboarded) throw new Error("Complete your Twin introduction first."); if (agentWorkspace.current.busy) throw new Error("Wait for the current reflection to finish."); setDialog(null); setTeam(null); setConversation(true); setQuestion(question.trim()); await new Promise<void>(resolve => requestAnimationFrame(() => requestAnimationFrame(() => resolve()))); return { status: "prepared", submitted: false }; } });
    return () => lifecycle.abort();
  }, []);
  if (!ready) return <main className="onboarding-loading" role="status">Opening your space…</main>;
  if (!onboardingCompleted) return <Onboarding initialProfile={profile} storageError={storageError} onComplete={next => { setProfile(next); setOnboardingCompleted(true); }} />;
  return <div className={`nook-app ${conversation ? "conversation-open" : ""}`}>
    <header className="nook-toolbar"><button className="brand-button" onClick={newConversation} disabled={busy} aria-label="Nook home"><Brand small /></button><div className="nook-utilities"><button onClick={() => setDialog("saved")}><BookOpen size={17} /><span>Saved</span></button><button onClick={() => setDialog("you")}><Fingerprint size={18} /><span>You</span></button></div><button ref={menuButton} className="icon-button nook-hamburger" aria-label={mobileMenu ? "Close menu" : "Open menu"} aria-expanded={mobileMenu} aria-controls="nook-mobile-menu" onClick={() => setMobileMenu(!mobileMenu)}>{mobileMenu ? <X size={22} /> : <Menu size={22} />}</button></header>
    {mobileMenu && <nav className="nook-mobile-menu" id="nook-mobile-menu" aria-label="More options">{[{ label: "Saved reflections", target: "saved" }, { label: "Your Twin preferences", target: "you" }, { label: "Privacy & live AI", target: "privacy" }].map(item => <button key={item.target} onClick={() => { setMobileMenu(false); setDialog(item.target as "saved" | "you" | "privacy"); }}>{item.label}<ChevronRight size={16} /></button>)}</nav>}
    <main className="nook-canvas">
      {!conversation ? <section className="nook-idle"><button className="nook-orb" onClick={activate} aria-label="Talk to Nook"><span className="nook-orb-core" aria-hidden="true"><i /><i /><i /><i /></span></button><span className="nook-orb-caption">A LITTLE SPACE, JUST FOR YOU</span><h1>What’s on your mind, {profile.name}?</h1><p>A decision. An idea. Something to untangle.</p><button className="nook-start" onClick={activate}>Talk to Nook</button><span className="nook-idle-hint">Your life, from a few thoughtful perspectives.</span></section> : <section className="nook-conversation">
        <div className="nook-conversation-header"><div><button className="nook-mini-orb" onClick={newConversation} disabled={busy} aria-label="Return to Nook"><span aria-hidden="true">n</span></button><span><strong>Nook</strong><small>{liveEnabled ? "Live council" : "Local preview"}</small></span></div><button className="text-button" onClick={newConversation} disabled={busy}>New conversation</button></div>
        <div className="nook-thread" role="log" aria-live="polite" aria-relevant="additions" aria-label="Your conversation">
          {!thread.length && !busy && <div className="conversation-welcome"><h2>Let’s make a little room.</h2><p>Tell me what you’re thinking about. We’ll find a next step together.</p><div className="prompt-suggestions">{examples.map(q => <button key={q} onClick={() => consult(q)}>{q}<ChevronRight size={16} /></button>)}</div></div>}
          {thread.map(d => <article className="chat-turn" key={d.id}><p className="chat-question">{d.question}</p><section className="reflection-card"><div className="reflection-heading"><span className="eyebrow"><Sparkles size={14} /> A THOUGHTFUL NEXT STEP</span><span>{d.mode === "live" ? "Live" : "Sample"}</span></div><h3>{d.recommendation || synthesis(d.kind, d.profileSnapshot || profile)}</h3><p className="reflection-values">Guided by {(d.profileSnapshot || profile).values.join(" · ")}</p><details className="reflection-perspectives"><summary>See the different perspectives <ChevronRight size={15} /></summary><div className="opinion-list">{(d.opinions || perspectives(d.kind, d.profileSnapshot || profile)).map((o, i) => { const t = teams[i]; return <article className="opinion" key={t.name}><button className={`lens-icon ${t.color}`} aria-label={`Meet the ${t.name} team`} onClick={() => { setTeam(i); setMessage(""); setReply(""); }}><t.icon size={20} /></button><div><div className="opinion-title"><h4>{t.name}</h4><span>{o.stance}</span></div><h4>{o.title}</h4><p>{o.opinion}</p></div></article>; })}</div></details><details className="critic-note"><summary>A counterpoint worth keeping</summary><p>{d.critique || "This is a starting point, based on the preferences you shared. Check the practical details and talk with anyone affected before deciding."}</p></details><div className="reflection-actions"><button className="text-button" disabled={d.saved} onClick={() => saveDecision(d)}><Check size={15} />{d.saved ? "Saved" : "Save next step"}</button><button className="text-button" onClick={() => { setQuestion(d.question); composer.current?.focus(); }}>Revisit</button></div></section>{d.kind === "social" && <section className="social-chat-card"><span className="eyebrow">A PLAN TO EXPLORE</span><h3>A walk. A long lunch. Good company.</h3><p>A sample Saturday with Maya, ready for your review.</p><div className="plan-meta"><span><CalendarDays size={15} /> Saturday · 11 AM</span><span><Coffee size={15} /> Walk & lunch</span></div><button className="secondary-button" onClick={() => showPlan()}>Review plan <ChevronRight size={16} /></button></section>}</article>)}
          {busy && <div className="chat-turn"><p className="chat-question">{pendingQuestion}</p><div className="thinking" role="status"><span className="thinking-icon"><Sparkles size={22} /></span><p>Making room for every perspective…</p></div></div>}
          {councilError && <p className="council-error" role="alert">{councilError}</p>}<div ref={threadEnd} />
        </div>
        <div className="nook-composer-dock"><form className="nook-composer" onSubmit={e => { e.preventDefault(); consult(question); }}><label className="sr-only" htmlFor="question">Message Nook</label><textarea ref={composer} id="question" rows={1} value={question} maxLength={1000} onChange={e => setQuestion(e.target.value)} onKeyDown={e => { if (e.key === "Enter" && !e.shiftKey && !e.nativeEvent.isComposing) { e.preventDefault(); consult(question); } }} placeholder="What’s on your mind?" /><button className="icon-button send-button" aria-label="Send message" disabled={busy || !question.trim()}><ArrowUp size={20} /></button></form><div className="composer-meta"><span>{liveEnabled ? "Live AI · your preferences guide the conversation" : "Local sample responses · saved on this device"}</span><button onClick={() => setDialog("privacy")}>Privacy <LockKeyhole size={11} /></button></div></div>
      </section>}
      {storageError && <p className="storage-warning" role="status">{storageError === "corrupt" ? "Saved data could not be read. Your previous data is preserved; new changes will last for this session until you reset local data." : "Browser storage is unavailable. Changes will last for this session only."}</p>}
    </main>
    <nav className="nook-bottom-nav" aria-label="Mobile navigation"><button className={!dialog && team === null ? "active" : ""} onClick={() => { close(); setMobileMenu(false); if (!busy) newConversation(); }}><Sun size={21} /><span>Today</span></button><button className={dialog === "council" || team !== null ? "active" : ""} onClick={() => { setMobileMenu(false); setTeam(null); setDialog("council"); }}><Compass size={21} /><span>Council</span></button><button className={dialog === "circle" || dialog === "plan" ? "active" : ""} onClick={() => { setMobileMenu(false); setTeam(null); setDialog("circle"); }}><Users size={21} /><span>Circle</span></button><button className={dialog === "you" || dialog === "profile" ? "active" : ""} onClick={() => { setMobileMenu(false); setTeam(null); setDialog("you"); }}><Fingerprint size={21} /><span>My Twin</span></button></nav>
    {dialog === "council" && <Modal title="Your personal council." onClose={close}><p className="modal-description">Good advice isn’t always agreement. Your wellbeing, ambition, and relationships each deserve a perspective.</p><div className="council-grid">{teams.map((t, i) => <button className="council-card" key={t.name} onClick={() => { setDialog(null); setTeam(i); setMessage(""); setReply(""); }}><span className={`lens-icon ${t.color}`}><t.icon size={22} /></span><div><h3>{t.name}</h3><p className="council-role">{t.specialty}</p><p className="council-quote">{t.insight}</p></div><ChevronRight size={17} /></button>)}</div><button className="primary-button council-start" onClick={() => { close(); activate(); }}><Sparkles size={16} /> Bring a question to your council</button></Modal>}
    {dialog === "circle" && <Modal title="Your people. A little closer." onClose={close}><p className="modal-description">Explore a shared plan with a friend’s Twin. Connections and conversations are clearly labeled samples in this first version.</p><section className="utility-section">{["Maya", "Sam", ...friends].map(name => <button className="utility-row" key={name} onClick={() => showPlan(name)}><Users size={18} /><span>{name}’s Twin<small>{friends.includes(name) ? "Local connection" : "Sample AI representative"} · {plans[name] === "saved" ? "Plan saved" : "Plan to explore"}</small></span><ChevronRight size={16} /></button>)}</section><button className="secondary-button" onClick={() => { setFriend(""); setDialog("invite"); }}><Plus size={17} /> Add a local connection</button></Modal>}
    {toast && <div className="toast" role="status"><Check size={17} />{toast}</div>}
    {dialog === "saved" && <Modal title="Room to come back to." onClose={close}><p className="modal-description">Your reflections and plans, kept on this device.</p><section className="utility-section"><h3>Reflections</h3>{decisions.length ? <div className="saved-list">{decisions.map(d => <button key={d.id} className="decision-row" onClick={() => revisit(d)}><span className="row-icon"><BookOpen size={18} /></span><span>{d.question}<small>{d.saved ? "Saved next step" : "Recent reflection"}</small></span><ChevronRight size={16} /></button>)}</div> : <p className="subtle">A conversation is a good place to start. Your reflections will appear here.</p>}</section><section className="utility-section"><h3>Your plans</h3>{["Maya", "Sam", ...friends].map(name => <button className="utility-row" key={name} onClick={() => showPlan(name)}><Users size={17} /><span>A Saturday with {name}<small>{plans[name] === "saved" ? "Saved plan" : plans[name] === "declined" ? "Set aside" : "Sample plan to review"}</small></span><ChevronRight size={16} /></button>)}</section></Modal>}
    {dialog === "you" && <Modal title="A little more you." onClose={close}><div className="you-summary"><Avatar text={profile.name.slice(0, 2).toUpperCase()} color="you-avatar" /><h3>{profile.name}</h3><p>{profile.priority}</p><div className="twin-values you-values">{profile.values.map(v => <span key={v}>{v}</span>)}</div><button className="secondary-button" onClick={edit}><SlidersHorizontal size={16} /> Edit your preferences</button></div><section className="utility-section"><h3>Your perspectives</h3>{teams.map((t, i) => <button className="utility-row" key={t.name} onClick={() => { setDialog(null); setTeam(i); setMessage(""); setReply(""); }}><span className={`lens-icon ${t.color}`}><t.icon size={19} /></span><span>{t.name}<small>{t.specialty}</small></span><ChevronRight size={16} /></button>)}</section><section className="utility-section"><h3>Your people</h3>{["Maya", "Sam", ...friends].map(name => <button className="utility-row" key={name} onClick={() => showPlan(name)}><Users size={17} /><span>{name}<small>{friends.includes(name) ? "Local connection" : "Sample connection"}</small></span><ChevronRight size={16} /></button>)}<button className="text-button" onClick={() => { setFriend(""); setDialog("invite"); }}><Plus size={16} /> Add a connection</button></section><button className="utility-row" onClick={() => setDialog("privacy")}><ShieldCheck size={18} /><span>Privacy & live AI<small>{liveEnabled ? "Live council enabled" : "Local preview"}</small></span><ChevronRight size={16} /></button></Modal>}
  {team !== null && <Modal title={teams[team].name} onClose={close}><p className="modal-description">A team of reasoning perspectives, guided by what matters to you.</p><div className="team-persons">{teams[team].members.map(m => <div key={m}><Avatar text={m.slice(0, 2).toUpperCase()} /><span><strong>{m.split(" · ")[0]}</strong><small>{m.split(" · ")[1]} · AI perspective</small></span></div>)}</div><p className="preview-note">Sample personas · reasoning perspectives, not professional advisers</p><form onSubmit={e => { e.preventDefault(); if (message.trim()) { const o = perspectives("reflection", profile)[team]; setReply(`${o.title}. ${o.opinion}`); } }}><label className="field-label" htmlFor="message">What would you like to explore?</label><div className="message-input"><input id="message" value={message} onChange={e => setMessage(e.target.value)} placeholder="Share a situation with this team…" maxLength={1000} required /><button className="icon-button send-button" aria-label="Get a sample perspective" disabled={!message.trim()}><ArrowUp size={20} /></button></div></form>{reply && <div className="team-reply" role="status"><span className="eyebrow">A SAMPLE PERSPECTIVE</span><p>{reply}</p><button className="text-button" onClick={() => consult(message)}>Bring this to the whole council <ChevronRight size={16} /></button></div>}</Modal>}
  {dialog === "profile" && <Modal title="Shape what your Twin knows." onClose={close}><p className="modal-description">Start with the things that matter. You can change your mind anytime.</p><form onSubmit={e => { e.preventDefault(); const result = profileSchema.safeParse(draft); if (!result.success) return; setProfile(result.data); close(); notify("Your Twin preferences have been updated."); }}><label className="field-label" htmlFor="name">What should we call you?</label><input id="name" value={draft.name} onChange={e => setDraft({ ...draft, name: e.target.value })} maxLength={30} required /><label className="field-label" htmlFor="priority">What matters most right now?</label><textarea id="priority" value={draft.priority} onChange={e => setDraft({ ...draft, priority: e.target.value })} maxLength={240} rows={3} required /><span className="field-label">Choose your values</span><div className="value-options">{["Wellbeing", "Meaningful work", "Time with people", "Learning", "Freedom", "Financial stability"].map(v => <button type="button" key={v} aria-pressed={draft.values.includes(v)} className={draft.values.includes(v) ? "selected" : ""} onClick={() => setDraft({ ...draft, values: draft.values.includes(v) ? draft.values.filter(x => x !== v) : [...draft.values, v] })}>{draft.values.includes(v) && <Check size={14} />}{v}</button>)}</div><label className="checkbox-row"><input type="checkbox" checked={draft.weekend} onChange={e => setDraft({ ...draft, weekend: e.target.checked })} /><span>Protect my weekends for rest and my people.</span></label><ProfileDetails profile={draft} onChange={setDraft} /><div className="form-actions"><span className="subtle">Saved only on this device</span><button className="primary-button" disabled={!draft.name.trim() || !draft.priority.trim() || !draft.values.length}>Save my preferences</button></div></form></Modal>}
  {dialog === "plan" && <Modal title="A Saturday worth making space for." onClose={close}><p className="preview-note">Sample negotiation · {friend}’s AI Twin</p><div className="negotiation"><p><strong>Your Twin</strong><span>A relaxed outdoor plan would fit. Let’s keep the afternoon open.</span></p><p><strong>{friend}’s AI Twin</strong><span>A late start works. A coastal walk and lunch is a shared starting point.</span></p></div><section className="proposed-plan"><span className="eyebrow">A PROPOSED PLAN</span><h3>Coastal walk & a long lunch</h3><p><CalendarDays size={17} /> Saturday · 11:00 AM – 2:00 PM</p><p><Compass size={17} /> Meet at the waterfront trail</p><p><Coffee size={17} /> Choose lunch together after the walk</p></section><section className="sharing-box"><h4><ShieldCheck size={16} /> You choose what to share</h4><label className="checkbox-row"><input type="checkbox" checked={shared.availability} onChange={e => setShared({ ...shared, availability: e.target.checked })} /><span>Saturday availability</span></label><label className="checkbox-row"><input type="checkbox" checked={shared.preference} onChange={e => setShared({ ...shared, preference: e.target.checked })} /><span>Outdoor activity preference</span></label><small>Your personal memories, health, and finances stay private.</small></section><p className="preview-note">Saving records your interest locally. {friend} has not been contacted and no booking is made.</p><div className="form-actions"><button className="text-button" onClick={() => { setPlans(old => ({ ...old, [friend]: "declined" })); close(); notify("The sample plan is set aside."); }}>Maybe another time</button><button className="primary-button" disabled={!shared.availability || !shared.preference || friendPlanStatus === "saved"} onClick={() => { setPlans(old => ({ ...old, [friend]: "saved" })); close(); notify("Sample plan saved. No message has been sent."); }}><Check size={16} />{friendPlanStatus === "saved" ? "Plan saved" : "Save this plan"}</button></div>{(!shared.availability || !shared.preference) && <p className="preview-note">Both details are needed for this sample plan. You can keep them private and set the plan aside.</p>}</Modal>}
  {dialog === "privacy" && <Modal title="Your space stays yours." onClose={close}>{[{ icon: LockKeyhole, title: "On this device", text: "Your workspace is saved in this browser’s local storage and is not synced to an account. Live council processing is separate: when enabled, your question, recent conversation, and your stated preferences and about-you answers are sent to OpenAI. Profile links stay on this device; Nook does not import social account data." }, { icon: Sparkles, title: "A transparent first version", text: "Preview council opinions and friend-Twin conversations are samples. Live council mode is available when a server key is configured. Calendars, bookings, and external friend agents are not connected." }, { icon: ShieldCheck, title: "You choose what leaves your space", text: "Plan review previews scoped sharing. This version does not send information or contact your friends." }].map(p => <div className="privacy-item" key={p.title}><p.icon size={22} /><div><h3>{p.title}</h3><p>{p.text}</p></div></div>)}<section className="live-setting"><h3>Live council</h3><p>{needsSignIn ? "Live council is configured. Sign in to enable it." : aiAvailable ? "An AI service is configured. When enabled, your question, recent conversation, and stated Twin preferences are sent to OpenAI for independent council reasoning." : "No AI key is configured. Your council works in local preview mode. Configure OPENAI_API_KEY on the server to enable live reasoning."}</p>{needsSignIn && <a className="text-button" href="/signin-with-chatgpt?return_to=/">Sign in to use the configured council</a>}<label className="checkbox-row"><input type="checkbox" checked={liveEnabled} disabled={!aiAvailable} onChange={e => setLiveEnabled(e.target.checked)} /><span>Use live AI for council decisions</span></label></section><button className="secondary-button" onClick={() => { try { localStorage.removeItem("nook.v1"); setCanPersist(true); setStorageError(null); } catch { setStorageError("unavailable"); setCanPersist(false); } requestController.current?.abort(); if (timer.current) clearTimeout(timer.current); setBusy(false); setLiveEnabled(false); setProfile(initial); setOnboardingCompleted(false); setDecisions([]); setThread([]); setQuestion(""); setPendingQuestion(""); setCouncilError(""); setConversation(false); setPlans({}); setFriends([]); close(); notify("This device’s workspace has been reset."); }}>Reset local preview data</button></Modal>}
  {dialog === "invite" && <Modal title="Make room for someone." onClose={close}><p className="modal-description">Add a local connection to explore the experience. Invitations and live Twin connections are not enabled in this preview.</p><form onSubmit={e => { e.preventDefault(); const name = friend.trim(); if (!name) return; if (friends.length >= 100) { notify("Your local circle is full. Up to 100 connections can be saved."); return; } if (["maya", "sam", ...friends.map(f => f.toLowerCase())].includes(name.toLowerCase())) { notify("That person is already in your circle."); return; } setFriends(old => [...old, name]); close(); notify("Local connection added. No invitation was sent."); }}><label className="field-label" htmlFor="friend">Their name</label><input id="friend" value={friend} onChange={e => setFriend(e.target.value)} placeholder="Someone you’d like to plan with" maxLength={30} required /><div className="form-actions"><button className="primary-button" disabled={!friend.trim()}><Plus size={16} /> Add local connection</button></div></form></Modal>}
  </div>;
}
